insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (52, 41636178, 'New York', 'New York City', 'Trumann Booth-Jarvis', 'Esch', '27156', 9377);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (56, 94050839, 'New York', 'Staten Island', 'Rosanne MacCague', 'Westerfield', '83227', 9721);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (29, 13471113, 'New York', 'Flushing', 'Ferdy Wicken', 'Rockefeller', '79', 5067);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (87, 26185915, 'New York', 'Albany', 'Jemimah Sayton', 'Kinsman', '87', 2140);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (45, 32811833, 'New York', 'Brooklyn', 'Nigel Aikin', 'Schiller', '4', 9270);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (34, 63104417, 'New York', 'New York City', 'Judith Bucknall', 'Kensington', '60221', 1560);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (88, 87548168, 'New York', 'Brooklyn', 'Brit Baldrey', '3rd', '6', 3658);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (62, 88017698, 'New York', 'New York City', 'Irita Madgewick', 'Vahlen', '00789', 5345);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (98, 94164072, 'New York', 'New York City', 'Ric Zukerman', 'Bultman', '9', 7251);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (47, 26162155, 'New York', 'New York City', 'Bradly Deboick', 'Lakewood', '14', 9613);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (28, 91785133, 'New York', 'Bronx', 'Damiano Robberts', 'Hollow Ridge', '371', 3086);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (6, 41124935, 'New York', 'Rochester', 'Nancie Lovemore', 'Marquette', '4161', 6478);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (93, 45962511, 'New York', 'Jamaica', 'Zelda Robertsson', 'Alpine', '3233', 8728);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (1, 79890083, 'New York', 'Rochester', 'Terencio Golton', 'Mifflin', '554', 5557);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (2, 54934287, 'New York', 'Hicksville', 'Cacilia Hasson', 'Jay', '199', 4078);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (2, 28298830, 'New York', 'New Hyde Park', 'Kala McCourtie', 'Cottonwood', '443', 8964);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (91, 78396061, 'New York', 'Albany', 'Gale Kensett', 'Portage', '05608', 5767);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (5, 10922617, 'New York', 'New York City', 'June Brownsill', 'Everett', '298', 2686);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (76, 15011144, 'New York', 'Rochester', 'Odie Fraine', 'Fairview', '01581', 9837);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (39, 99662268, 'New York', 'Bronx', 'Hymie Tappin', 'International', '790', 2394);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (97, 56676566, 'New York', 'Elmira', 'Raeann Heintz', 'Graedel', '73', 1000);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (99, 58631826, 'New York', 'New York City', 'Rawley McGuffog', 'Burning Wood', '30631', 5645);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (68, 93365143, 'New York', 'New York City', 'Silva Bryan', 'Hayes', '7150', 6793);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (42, 27027194, 'New York', 'Brooklyn', 'Alexandrina Tremontana', 'Debra', '30920', 1293);
insert into Enderecos (id, cep, estado, cidade, bairro, rua, numero, complemento) values (1, 90250353, 'New York', 'Bronx', 'Briney Caldayrou', 'Hoard', '7921', 5381);
